name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  LC_CTYPE: en_US.UTF-8
  LANG: en_US.UTF-8

jobs:
  build:
    name: Build (${{ matrix.mode }})
    runs-on: macos-latest
    
    strategy:
      matrix:
        mode: [framework, spm, examples]
      fail-fast: false
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Show Xcode version
        run: xcodebuild -version
      
      - name: Install CocoaPods
        run: gem install cocoapods --pre
      
      - name: Build and test
        run: ./build.sh ${{ matrix.mode }}

